language: c
compiler: gcc
sudo: false

dist: bionic
addons:
  apt:
    update: true
    packages:
      - cmake-data
      - cmake
      - lcov
      - valgrind
      - ftp
      - lftp

script:
  - cd build/
  - cmake -D CMAKE_BUILD_TYPE=Release ..
  - make
  #- cd ../profiling
  #- ./memcheck.sh 42
  #- ./memcheck.sh 0x42
  #- ./memcheck.sh 42h
  #- ./memcheck.sh 101010b
  #- cd ../test/functional/
  #- ./functional_test.sh
  - cd ../coverage/
  - ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file:
    - vs-ftp
  skip_cleanup: true
  on:
    tags: true
